<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://das.dogane.finanze.it" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://das.dogane.finanze.it" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- versione 1.0 del 03/07/2020 -->
	<xs:include schemaLocation="DAS_SimpleTypes.xsd"/>
	<xs:element name="DE818">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="attributiMessaggio" type="AttributiMessaggio"/>
				<xs:element name="notaDiRicevimento" type="NotaDiRicevimento"/>
				<xs:element name="dettaglioNotaDiRicevimento" type="DettaglioNotaDiRicevimento" maxOccurs="999"/>
				<xs:element name="datiFatturazione" type="DatiFatturazione" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AttributiMessaggio">
		<xs:sequence>
			<xs:element name="MessageCode" type="xs:string" fixed="DE818"/>
			<xs:element name="DeclaratorIdentifyCode">
				<xs:annotation>
					<xs:documentation>Modifica del pattern per codice fiscale che tiene conto della omocodia</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z]{6}[0-9]{2}[A-Z]{1}[A-Z0-9]{7}|IT[0-9]{11}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Filename" type="an..25"/>
			<xs:element name="ConsignorExciseNumber">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="IT00[A-Z0-9]{9}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="IdentifynumberSRC" type="an21Upper"/>
			<xs:element name="SeqNumber" type="Prog1-99"/>
			<xs:element name="ConsigneeTraderid" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:maxLength value="16" />
						<xs:pattern value=".{1,16}" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DeliveryPlaceTraderid" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:maxLength value="16" />
						<xs:pattern value=".{1,16}" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NotaDiRicevimento">
		<xs:sequence>
			<xs:element name="DateOfArrivalExciseProducts" type="xs:date"/>
			<xs:element name="GlobalConclusionOfReceipt" type="Int0-9" minOccurs="0"/>
			<xs:element name="ComplementaryInformation" type="an..350" minOccurs="0"/>
			<xs:element name="ComplementaryInformationLNG" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-z]{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DettaglioNotaDiRicevimento">
		<xs:sequence>
			<xs:element name="BodyRecordUniqueReference" type="Prog1-999"/>
			<xs:element name="IndicatorOfShortageOrExcess" type="IndicatorOfShortageOrExcessType" minOccurs="0"/>
			<xs:element name="ObservedShortageOrExcess" type="Dec12.3" minOccurs="0"/>
			<xs:element name="CompleteExciseProductCode" type="an..18" minOccurs="0"/>
			<xs:element name="InitialCounterReading" type="Dec12.2" minOccurs="0"/>
			<xs:element name="FinalCounterReading" type="Dec12.2" minOccurs="0"/>
			<xs:element name="Volume" type="Dec13.2" minOccurs="0"/>
			<xs:element name="Temperature" type="Int-99-99" minOccurs="0"/>
			<xs:element name="Density" type="Dec4.2" minOccurs="0"/>
			<xs:element name="Density15" type="Dec4.2" minOccurs="0"/>
			<xs:element name="DocumentImage" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:base64Binary"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CarichiGiacenze" type="CarichiGiacenze" minOccurs="0" maxOccurs="9"/>
			<xs:element name="MotivoDiInsoddisfazioneDettaglio" type="MotivoDiInsoddisfazioneDettaglio" minOccurs="0" maxOccurs="9"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CarichiGiacenze">
		<xs:sequence>
			<xs:element name="StockinventoryIdentifier" type="an..4" minOccurs="0"/>
			<xs:element name="AcceptedQuantity" type="Dec12.3" minOccurs="0"/>
			<xs:element name="IdRiga" type="Int0-9999999999"/>
			<xs:element name="IdTank" type="an..20" minOccurs="0"/>
			<xs:element name="TimeStart" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="TimeEnd" type="xs:dateTime" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MotivoDiInsoddisfazioneDettaglio">
		<xs:sequence>
			<xs:element name="UnsatisfactoryReasonNumber" type="Prog1-9"/>
			<xs:element name="UnsatisfactoryReasonCode" type="Int0-9" minOccurs="0"/>
			<xs:element name="ComplementaryInformation" type="an..350" minOccurs="0"/>
			<xs:element name="ComplementaryInformationLNG" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-z]{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DatiFatturazione">
		<xs:sequence>
			<xs:element name="InvoiceNumber" type="an..35"/>
			<xs:element name="InvoiceDate" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
