<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://das.dogane.finanze.it" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://das.dogane.finanze.it" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- versione 1.0 del 03/07/2020-->
	<xs:include schemaLocation="DAS_SimpleTypes.xsd"/>
	<xs:element name="DE813">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="attributiMessaggio" type="AttributiMessaggio"/>
				<xs:element name="dasElettronico" type="DasElettronico"/>
				<xs:element name="nuovoDestinatario" type="NuovoDestinatario"/>
				<xs:element name="nuovoLuogoDiDestinazioneConsegna" type="NuovoLuogoDiDestinazioneConsegna"/>
				<xs:element name="autFiscCompDestinatario" type="AutFiscCompDestinatario"/>
				<xs:element name="primoVettore" type="PrimoVettore"/>
				<xs:element name="primoTrasportatore" type="PrimoTrasportatore" minOccurs="0"/>
				<xs:element name="incaricatoTrasporto" type="IncaricatoTrasporto" minOccurs="0"/>
				<xs:element name="dettaglioTrasporto" type="DettaglioTrasporto" maxOccurs="99"/>
				<xs:element name="depositante" type="Depositante" minOccurs="0"/>
				<xs:element name="primoCessionario" type="PrimoCessionario" minOccurs="0"/>
				<xs:element name="merci" type="Merci" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AttributiMessaggio">
		<xs:sequence>
			<xs:element name="MessageCode" type="xs:string" fixed="DE813"/>
			<xs:element name="DeclaratorIdentifyCode">
				<xs:annotation>
					<xs:documentation>Modifica del pattern per codice fiscale che tiene conto della omocodia</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z]{6}[0-9]{2}[A-Z]{1}[A-Z0-9]{7}|IT[0-9]{11}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Filename" type="an..25"/>
			<xs:element name="ConsignorExciseNumber">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="IT00[A-Z0-9]{9}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Identifynumber" type="an21Upper"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DasElettronico">
		<xs:sequence>
			<xs:element name="MesurementJourneyType" type="xs:string" fixed="H"/>
			<xs:element name="JourneyTime" type="Int1-99"/>
			<xs:element name="TransportArrangement" type="Int0-9"/>
			<xs:element name="TransportModeCode" type="Int0-99"/>
			<xs:element name="ComplementaryInformation" type="an..350" minOccurs="0"/>
			<xs:element name="Language" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-z]{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ISO3166Code" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z]{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GuarantorTypeCode" type="Int0-99" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NuovoDestinatario">
		<xs:sequence>
			<xs:element name="DestinationTypeCode" type="Int0-99"/>
			<xs:element name="InvoiceNumber" type="an..35" minOccurs="0"/>
			<xs:element name="InvoiceDate" type="xs:date" minOccurs="0"/>
			<xs:element name="ConsigneeTraderid">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:maxLength value="16" />
						<xs:pattern value=".{1,16}" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ConsigneeTraderName" type="an..182" minOccurs="0"/>
			<xs:element name="ConsigneeStreetName" type="an..65" minOccurs="0"/>
			<xs:element name="ConsigneeStreetNumber" type="an..11" minOccurs="0"/>
			<xs:element name="ConsigneePostcode" type="an..10" minOccurs="0"/>
			<xs:element name="ConsigneeCity" type="an..50" minOccurs="0"/>
			<xs:element name="ConsigneeLanguage" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="it"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NuovoLuogoDiDestinazioneConsegna">
		<xs:sequence>
			<xs:element name="DeliveryPlaceTraderid">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:maxLength value="16" />
						<xs:pattern value=".{1,16}" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DeliveryPlaceTraderName" type="an..182" minOccurs="0"/>
			<xs:element name="DeliveryPlaceStreetName" type="an..65" minOccurs="0"/>
			<xs:element name="DeliveryPlaceStreetNumber" type="an..11" minOccurs="0"/>
			<xs:element name="DeliveryPlacePostcode" type="an..10" minOccurs="0"/>
			<xs:element name="DeliveryPlaceCity" type="an..50" minOccurs="0"/>
			<xs:element name="DeliveryPlaceLanguage" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="it"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ShipFlag" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z]{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AutFiscCompDestinatario">
		<xs:sequence>
			<xs:element name="ReferenceNumber" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="IT[0-9]{6}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PrimoVettore">
		<xs:sequence>
			<xs:element name="TransportTraderVatNumber">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="IT[0-9]{11}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PrimoTrasportatore">
		<xs:sequence>
			<xs:element name="FirstTrVatNumber">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="IT[0-9]{11}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IncaricatoTrasporto">
		<xs:sequence>
			<xs:element name="DriverSurname" type="an1..50"/>
			<xs:element name="DriverName" type="an1..50"/>
			<xs:element name="DriverNationality" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z]{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DriverID" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Modifica del pattern per codice fiscale che tiene conto della omocodia</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z]{6}[0-9]{2}[A-Z]{1}[A-Z0-9]{7}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DriverADR" type="an1..30" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DettaglioTrasporto">
		<xs:sequence>
			<xs:element name="TransportIterationNumber" type="Prog1-99"/>
			<xs:element name="TransportUnitCode" type="Int0-99"/>
			<xs:element name="IdentityOfTransportUnits" type="an1..35" minOccurs="0"/>
			<xs:element name="CommercialSealIdentification" type="an1..35" minOccurs="0"/>
			<xs:element name="SealInformation" type="an1..350" minOccurs="0"/>
			<xs:element name="SealInfoLanguage" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-z]{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="TransDetailInfo" type="an1..350" minOccurs="0"/>
			<xs:element name="TransDetailInfoLanguage" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-z]{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Depositante">
		<xs:sequence>
			<xs:element name="HolderNumber" type="an..22"/>
			<xs:element name="HolderName" type="an..182"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PrimoCessionario">
		<xs:sequence>
			<xs:element name="TraderNumber">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="IT[0-9]{11}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Merci">
		<xs:sequence>
			<xs:element name="DettaglioMerci" type="DettaglioMerci" maxOccurs="999"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DettaglioMerci">
		<xs:sequence>
			<xs:element name="GoodIterationNumber" type="Prog1-999"/>
			<xs:element name="CPAProductCategory">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z0-9]{4}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CnCode" type="Int0-99999999"/>
			<xs:element name="Quantity" type="Dec12.3" minOccurs="0"/>
			<xs:element name="Volume" type="Dec13.2" minOccurs="0"/>
			<xs:element name="NetWeight" type="Dec13.2" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
